// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alarm.proto

package daemon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Alarm_Recurrence int32

const (
	Alarm_NO_RECURRENCE Alarm_Recurrence = 0
	Alarm_HOURLY        Alarm_Recurrence = 1
	Alarm_DAILY         Alarm_Recurrence = 2
)

var Alarm_Recurrence_name = map[int32]string{
	0: "NO_RECURRENCE",
	1: "HOURLY",
	2: "DAILY",
}
var Alarm_Recurrence_value = map[string]int32{
	"NO_RECURRENCE": 0,
	"HOURLY":        1,
	"DAILY":         2,
}

func (x Alarm_Recurrence) String() string {
	return proto.EnumName(Alarm_Recurrence_name, int32(x))
}
func (Alarm_Recurrence) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{6, 0}
}

type Time_Format int32

const (
	Time_TWENTYFOUR Time_Format = 0
	Time_AM         Time_Format = 1
	Time_PM         Time_Format = 2
)

var Time_Format_name = map[int32]string{
	0: "TWENTYFOUR",
	1: "AM",
	2: "PM",
}
var Time_Format_value = map[string]int32{
	"TWENTYFOUR": 0,
	"AM":         1,
	"PM":         2,
}

func (x Time_Format) String() string {
	return proto.EnumName(Time_Format_name, int32(x))
}
func (Time_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{7, 0}
}

type SetAlarmRequest struct {
	Alarm                *Alarm   `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmRequest) Reset()         { *m = SetAlarmRequest{} }
func (m *SetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*SetAlarmRequest) ProtoMessage()    {}
func (*SetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{0}
}
func (m *SetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmRequest.Unmarshal(m, b)
}
func (m *SetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmRequest.Marshal(b, m, deterministic)
}
func (dst *SetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmRequest.Merge(dst, src)
}
func (m *SetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_SetAlarmRequest.Size(m)
}
func (m *SetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmRequest proto.InternalMessageInfo

func (m *SetAlarmRequest) GetAlarm() *Alarm {
	if m != nil {
		return m.Alarm
	}
	return nil
}

type SetAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAlarmResponse) Reset()         { *m = SetAlarmResponse{} }
func (m *SetAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*SetAlarmResponse) ProtoMessage()    {}
func (*SetAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{1}
}
func (m *SetAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAlarmResponse.Unmarshal(m, b)
}
func (m *SetAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAlarmResponse.Marshal(b, m, deterministic)
}
func (dst *SetAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAlarmResponse.Merge(dst, src)
}
func (m *SetAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_SetAlarmResponse.Size(m)
}
func (m *SetAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAlarmResponse proto.InternalMessageInfo

type GetAlarmsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlarmsRequest) Reset()         { *m = GetAlarmsRequest{} }
func (m *GetAlarmsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlarmsRequest) ProtoMessage()    {}
func (*GetAlarmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{2}
}
func (m *GetAlarmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlarmsRequest.Unmarshal(m, b)
}
func (m *GetAlarmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlarmsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAlarmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlarmsRequest.Merge(dst, src)
}
func (m *GetAlarmsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlarmsRequest.Size(m)
}
func (m *GetAlarmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlarmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlarmsRequest proto.InternalMessageInfo

type GetAlarmsResponse struct {
	Alarms               []*Alarm `protobuf:"bytes,1,rep,name=alarms,proto3" json:"alarms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlarmsResponse) Reset()         { *m = GetAlarmsResponse{} }
func (m *GetAlarmsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlarmsResponse) ProtoMessage()    {}
func (*GetAlarmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{3}
}
func (m *GetAlarmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlarmsResponse.Unmarshal(m, b)
}
func (m *GetAlarmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlarmsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAlarmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlarmsResponse.Merge(dst, src)
}
func (m *GetAlarmsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlarmsResponse.Size(m)
}
func (m *GetAlarmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlarmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlarmsResponse proto.InternalMessageInfo

func (m *GetAlarmsResponse) GetAlarms() []*Alarm {
	if m != nil {
		return m.Alarms
	}
	return nil
}

type RemoveAlarmRequest struct {
	AlarmId              int32    `protobuf:"varint,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAlarmRequest) Reset()         { *m = RemoveAlarmRequest{} }
func (m *RemoveAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAlarmRequest) ProtoMessage()    {}
func (*RemoveAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{4}
}
func (m *RemoveAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAlarmRequest.Unmarshal(m, b)
}
func (m *RemoveAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAlarmRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAlarmRequest.Merge(dst, src)
}
func (m *RemoveAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAlarmRequest.Size(m)
}
func (m *RemoveAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAlarmRequest proto.InternalMessageInfo

func (m *RemoveAlarmRequest) GetAlarmId() int32 {
	if m != nil {
		return m.AlarmId
	}
	return 0
}

type RemoveAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAlarmResponse) Reset()         { *m = RemoveAlarmResponse{} }
func (m *RemoveAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveAlarmResponse) ProtoMessage()    {}
func (*RemoveAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{5}
}
func (m *RemoveAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAlarmResponse.Unmarshal(m, b)
}
func (m *RemoveAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAlarmResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAlarmResponse.Merge(dst, src)
}
func (m *RemoveAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveAlarmResponse.Size(m)
}
func (m *RemoveAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAlarmResponse proto.InternalMessageInfo

type Alarm struct {
	Id                   int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 *Time            `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Recurrence           Alarm_Recurrence `protobuf:"varint,3,opt,name=recurrence,proto3,enum=daemon.Alarm_Recurrence" json:"recurrence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Alarm) Reset()         { *m = Alarm{} }
func (m *Alarm) String() string { return proto.CompactTextString(m) }
func (*Alarm) ProtoMessage()    {}
func (*Alarm) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{6}
}
func (m *Alarm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alarm.Unmarshal(m, b)
}
func (m *Alarm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alarm.Marshal(b, m, deterministic)
}
func (dst *Alarm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alarm.Merge(dst, src)
}
func (m *Alarm) XXX_Size() int {
	return xxx_messageInfo_Alarm.Size(m)
}
func (m *Alarm) XXX_DiscardUnknown() {
	xxx_messageInfo_Alarm.DiscardUnknown(m)
}

var xxx_messageInfo_Alarm proto.InternalMessageInfo

func (m *Alarm) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alarm) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Alarm) GetRecurrence() Alarm_Recurrence {
	if m != nil {
		return m.Recurrence
	}
	return Alarm_NO_RECURRENCE
}

type Time struct {
	Hours                int32       `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes              int32       `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	Seconds              int32       `protobuf:"varint,3,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Format               Time_Format `protobuf:"varint,4,opt,name=format,proto3,enum=daemon.Time_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_alarm_7299878a9fe9634b, []int{7}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (dst *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(dst, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetHours() int32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

func (m *Time) GetMinutes() int32 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *Time) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Time) GetFormat() Time_Format {
	if m != nil {
		return m.Format
	}
	return Time_TWENTYFOUR
}

func init() {
	proto.RegisterType((*SetAlarmRequest)(nil), "daemon.SetAlarmRequest")
	proto.RegisterType((*SetAlarmResponse)(nil), "daemon.SetAlarmResponse")
	proto.RegisterType((*GetAlarmsRequest)(nil), "daemon.GetAlarmsRequest")
	proto.RegisterType((*GetAlarmsResponse)(nil), "daemon.GetAlarmsResponse")
	proto.RegisterType((*RemoveAlarmRequest)(nil), "daemon.RemoveAlarmRequest")
	proto.RegisterType((*RemoveAlarmResponse)(nil), "daemon.RemoveAlarmResponse")
	proto.RegisterType((*Alarm)(nil), "daemon.Alarm")
	proto.RegisterType((*Time)(nil), "daemon.Time")
	proto.RegisterEnum("daemon.Alarm_Recurrence", Alarm_Recurrence_name, Alarm_Recurrence_value)
	proto.RegisterEnum("daemon.Time_Format", Time_Format_name, Time_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlarmServiceClient is the client API for AlarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlarmServiceClient interface {
	SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error)
	GetAlarms(ctx context.Context, in *GetAlarmsRequest, opts ...grpc.CallOption) (*GetAlarmsResponse, error)
	RemoveAlarm(ctx context.Context, in *RemoveAlarmRequest, opts ...grpc.CallOption) (*RemoveAlarmResponse, error)
}

type alarmServiceClient struct {
	cc *grpc.ClientConn
}

func NewAlarmServiceClient(cc *grpc.ClientConn) AlarmServiceClient {
	return &alarmServiceClient{cc}
}

func (c *alarmServiceClient) SetAlarm(ctx context.Context, in *SetAlarmRequest, opts ...grpc.CallOption) (*SetAlarmResponse, error) {
	out := new(SetAlarmResponse)
	err := c.cc.Invoke(ctx, "/daemon.AlarmService/SetAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) GetAlarms(ctx context.Context, in *GetAlarmsRequest, opts ...grpc.CallOption) (*GetAlarmsResponse, error) {
	out := new(GetAlarmsResponse)
	err := c.cc.Invoke(ctx, "/daemon.AlarmService/GetAlarms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmServiceClient) RemoveAlarm(ctx context.Context, in *RemoveAlarmRequest, opts ...grpc.CallOption) (*RemoveAlarmResponse, error) {
	out := new(RemoveAlarmResponse)
	err := c.cc.Invoke(ctx, "/daemon.AlarmService/RemoveAlarm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmServiceServer is the server API for AlarmService service.
type AlarmServiceServer interface {
	SetAlarm(context.Context, *SetAlarmRequest) (*SetAlarmResponse, error)
	GetAlarms(context.Context, *GetAlarmsRequest) (*GetAlarmsResponse, error)
	RemoveAlarm(context.Context, *RemoveAlarmRequest) (*RemoveAlarmResponse, error)
}

func RegisterAlarmServiceServer(s *grpc.Server, srv AlarmServiceServer) {
	s.RegisterService(&_AlarmService_serviceDesc, srv)
}

func _AlarmService_SetAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).SetAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.AlarmService/SetAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).SetAlarm(ctx, req.(*SetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_GetAlarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlarmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).GetAlarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.AlarmService/GetAlarms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).GetAlarms(ctx, req.(*GetAlarmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmService_RemoveAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServiceServer).RemoveAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.AlarmService/RemoveAlarm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServiceServer).RemoveAlarm(ctx, req.(*RemoveAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlarmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.AlarmService",
	HandlerType: (*AlarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAlarm",
			Handler:    _AlarmService_SetAlarm_Handler,
		},
		{
			MethodName: "GetAlarms",
			Handler:    _AlarmService_GetAlarms_Handler,
		},
		{
			MethodName: "RemoveAlarm",
			Handler:    _AlarmService_RemoveAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alarm.proto",
}

func init() { proto.RegisterFile("alarm.proto", fileDescriptor_alarm_7299878a9fe9634b) }

var fileDescriptor_alarm_7299878a9fe9634b = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0xbd, 0x8a, 0xa5, 0x24, 0xcf, 0x89, 0xab, 0x4c, 0x5a, 0xaa, 0xb8, 0x17, 0xa3, 0x52,
	0x30, 0x14, 0x54, 0x70, 0x21, 0x94, 0x5e, 0x8a, 0x9b, 0x3a, 0x4d, 0x20, 0xb1, 0xcb, 0xc6, 0xa6,
	0xf8, 0x14, 0x5c, 0x6b, 0x4a, 0x05, 0x95, 0x94, 0xee, 0xca, 0xf9, 0x4a, 0x3d, 0xf4, 0x33, 0xf5,
	0xbb, 0x04, 0xad, 0xfe, 0xc4, 0x8e, 0x7d, 0x12, 0x33, 0xbf, 0xb7, 0xb3, 0x6f, 0xa4, 0x27, 0xb4,
	0xe6, 0xbf, 0xe7, 0x2a, 0x0e, 0xee, 0x54, 0x9a, 0xa5, 0xe4, 0x84, 0x73, 0x8e, 0xd3, 0xc4, 0x3f,
	0xc5, 0xb3, 0x1b, 0xce, 0x06, 0x39, 0x91, 0xfc, 0x67, 0xc9, 0x3a, 0xa3, 0xd7, 0xb0, 0x8d, 0xd2,
	0x13, 0x5d, 0xd1, 0x6b, 0xf5, 0x0f, 0x83, 0x42, 0x1a, 0x14, 0xa2, 0x82, 0xf9, 0x04, 0xf7, 0xf1,
	0x9c, 0xbe, 0x4b, 0x13, 0xcd, 0x79, 0xef, 0x6b, 0xd9, 0xd3, 0xe5, 0x30, 0xff, 0x23, 0x8e, 0x56,
	0x7a, 0x85, 0x90, 0xde, 0xc0, 0x31, 0x53, 0xb4, 0x27, 0xba, 0x3b, 0x9b, 0x57, 0x94, 0xd0, 0x7f,
	0x07, 0x92, 0x1c, 0xa7, 0xf7, 0xbc, 0x66, 0xef, 0x04, 0x7b, 0x86, 0xdf, 0x46, 0xa1, 0x71, 0x68,
	0xcb, 0x5d, 0x53, 0x5f, 0x86, 0xfe, 0x0b, 0x1c, 0xaf, 0x1d, 0x28, 0x7d, 0xfd, 0x13, 0xb0, 0x4d,
	0x87, 0xda, 0xb0, 0xea, 0x53, 0x56, 0x14, 0x52, 0x17, 0xcd, 0x2c, 0x8a, 0xd9, 0xb3, 0xcc, 0xa6,
	0x07, 0x95, 0x8d, 0x49, 0x14, 0xb3, 0x34, 0x84, 0x3e, 0x00, 0x8a, 0x17, 0x4b, 0xa5, 0x38, 0x59,
	0xb0, 0xb7, 0xd3, 0x15, 0xbd, 0x76, 0xdf, 0x5b, 0xb3, 0x1b, 0xc8, 0x9a, 0xcb, 0x15, 0xad, 0x7f,
	0x0a, 0x3c, 0x12, 0x3a, 0xc2, 0xe1, 0x68, 0x7c, 0x2b, 0x87, 0x67, 0x53, 0x29, 0x87, 0xa3, 0xb3,
	0xa1, 0xdb, 0x20, 0xc0, 0xb9, 0x18, 0x4f, 0xe5, 0xd5, 0xcc, 0x15, 0xb4, 0x0f, 0xfb, 0xcb, 0xe0,
	0xf2, 0x6a, 0xe6, 0x5a, 0xfe, 0x5f, 0x81, 0x66, 0x6e, 0x80, 0x9e, 0xc3, 0xfe, 0x95, 0x2e, 0x95,
	0x2e, 0xfd, 0x16, 0x05, 0x79, 0xd8, 0x8d, 0xa3, 0x64, 0x99, 0xb1, 0x36, 0xae, 0x6d, 0x59, 0x95,
	0x39, 0xd1, 0xbc, 0x48, 0x93, 0x50, 0x1b, 0x9f, 0xb6, 0xac, 0x4a, 0x7a, 0x0b, 0xe7, 0x67, 0xaa,
	0xe2, 0x79, 0xe6, 0x35, 0xcd, 0x02, 0xc7, 0xab, 0x8b, 0x06, 0xe7, 0x06, 0xc9, 0x52, 0xe2, 0xf7,
	0xe0, 0x14, 0x1d, 0x6a, 0x03, 0x93, 0xef, 0xc3, 0xd1, 0x64, 0x76, 0x3e, 0x9e, 0x4a, 0xb7, 0x41,
	0x0e, 0xac, 0xc1, 0xb5, 0x2b, 0xf2, 0xe7, 0xb7, 0x6b, 0xd7, 0xea, 0xff, 0x17, 0x38, 0x30, 0xaf,
	0xe0, 0x86, 0xd5, 0x7d, 0xb4, 0x60, 0xfa, 0x84, 0xbd, 0x2a, 0x14, 0xf4, 0xb2, 0xba, 0xe3, 0x49,
	0xbc, 0x3a, 0xde, 0x26, 0x28, 0xbf, 0x53, 0x83, 0x3e, 0x63, 0xbf, 0x4e, 0x0b, 0xd5, 0xc2, 0xa7,
	0xa1, 0xea, 0x9c, 0x6c, 0x21, 0xf5, 0x8c, 0x0b, 0xb4, 0x56, 0x42, 0x40, 0x9d, 0x4a, 0xbb, 0x19,
	0xa5, 0xce, 0xab, 0xad, 0xac, 0x9a, 0xf4, 0xc3, 0x31, 0xbf, 0xca, 0xfb, 0x87, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0x5c, 0xa7, 0x49, 0x39, 0x03, 0x00, 0x00,
}
